name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Unzip some tests
      run: find . -name '*.zip' -execdir unzip {} \;

    - name: Build & Test
      run: python3 ./test_all.py

